[project]
name = "agent-evaluator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "divu050704", email = "divyanshu14472@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "deepeval>=4.2.2",
    "langgraph>=1.2.11",
]

[project.scripts]
agent-evaluator = "agent_evaluator:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
